// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils"; // comes from ShadCN
import Sidebar from "@/components/ui/sidebar";
import Footer from "@/components/ui/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alfredo App",
  description: "Alfredo Dashboard Layout",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex min-h-screen")}>
        <Sidebar />
        <div className="ml-80 flex-1 flex flex-col">
          <main className="flex-1 p-4 bg-muted/40">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}



/* import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
} */
